version: '3.8'

services:
  sample.cache.api:
    build:
      target: build
    volumes:
      - ..:/src
      - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
      - ${HOME}/.dotnet:/root/.dotnet:ro
    entrypoint: sleep infinity
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - Caching__Enabled=true
      - Caching__DefaultTimeToLiveSeconds=60
      - Redis__ConnectionString=redis:6379,abortConnect=false
    network_mode: service:redis

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - cache-network
    depends_on:
      - redis
    restart: unless-stopped